[project]
name = "nde_auto_restart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "temporalio>=1.18.0",
    "watchfiles>=1.1.0",
]
